[package]
name = "zakary/newtycoon"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@0.5.0"
Timer = "sleitnick/timer@1.1.2"
Comm = "sleitnick/comm@0.3.1"
Component = "sleitnick/component@2.4.6"
Shake = "sleitnick/shake@0.1.7"
Roact = "roblox/roact@1.4.4"
Rodux = "roblox/rodux@3.0.0"
RoactRodux = "roblox/roact-rodux@0.5.1"
Knit = "sleitnick/knit@1.5.1"
Promise = "evaera/promise@4.0.0"
ProfileService = "nidoxs/profileservice@1.0.0"
Silo = "sleitnick/silo@0.1.1"